name: sprintf
version: 4.0.0
author: Richard Eames <dartsprintf@naddiseo.ca>
description: Dart implementation of sprintf
homepage: https://github.com/Naddiseo/dart-sprintf

dev_dependencies:
  test: any
